### ISSUE TITLE
Installer closes all open programs and tries to force a restart

### ISSUE THREAD

**Issue by dignakov** [fougue/mayo#152]
The app looks great, but as it was finishing installing it closed everything and tried rebooting the computer without my input or confirmation (Windows installer). This could cause people to loose work.

**Comment by HuguesDelorme** [comment]
Hello @dignakov 
That's weird I've never experienced that behavior when testing Mayo's InnoSetup installer within a Win7 virtual machine.
There's also no such instruction in the InnoSetup script to close all apps and request reboot.
Maybe that's caused by the MSVC redistributable package which is executed at the end of installation.

**Comment by dignakov** [comment]
That could be it. I can try re-installing now that I've the MSVC pack there already. Also, should have been more specific, this is on Win 10.

Let me know if you want me to try anything else.

**Comment by HuguesDelorme** [comment]
Hi again @dignakov
Yes that would be relevant to try install Mayo again and check if reboot is still required.
Thanks!

**Comment by HuguesDelorme** [comment]
No update
