### ISSUE TITLE
Avoid usage of Visual C++ redistributable with InnoSetup installer

### ISSUE THREAD

**Issue by HuguesDelorme** [fougue/mayo#266]
The InnoSetup installer embeds the Visual C++ redistributable component which is launched at last step, to install Visual C++ runtime DLLs
Let's remove it from the installer and instead explicitly deploy needed Visual C++ runtime DLLs

**Comment by HuguesDelorme** [comment]
Will be available for coming 0.9.0 version

**Comment by machinekoder** [comment]
Just came here randomly. You could also just set /silent for the vcredist install. Writing this here because we are switching from deployment of the runtime to the vcredist in a desktop application because it the deployed libs can be accidentally mixed together with sys libs and cause all sorts of heap corruptions and crashes (e.g. One Drive For Business pullung in a different version via file open dialog). If you ever encounter such problems, think about this.
