### ISSUE TITLE
Why did the release version not use 'cmakelists. txt' to organize code (I am a novice)

### ISSUE THREAD

**Issue by B1SH0PP** [fougue/mayo#275]
Why did the release version not use 'cmakelists. txt' to organize code?

**Comment by HuguesDelorme** [comment]
QMake was the makefile generator used until recently, see https://github.com/fougue/mayo/issues/53#issuecomment-1971657219
Qt is a foundation of Mayo it was natural to use QMake back then but as project grew over time then it made migration to CMake not a trivial task. It was delayed during a rather long time, but since a few months CMake is the build system used by Mayo.

**Comment by B1SH0PP** [comment]
Thank you for your clarification.
