### ISSUE TITLE
it is not in the center of view, it is situated in the left top corner!

### ISSUE THREAD

**Issue by dansirming** [fougue/mayo#76]
today， I have found  a new problem!  when I imported some steps into mayo ,but it is not in the center of view, it is situated in the left top corner. it is not perfect! it is difficult to use。the test step file in the  mail attachments。can you help me ?
[888.zip](https://github.com/fougue/mayo/files/6680105/888.zip)

**Comment by HuguesDelorme** [comment]
The problem is caused by the part in 888.step being located far in X negative (around -1250) and the 3D origin trihedron is taken into account in the "fit all" action (it should not).
As a temporary workaround you can disable this option :
![image](https://user-images.githubusercontent.com/939132/122672544-4ff63080-d1cc-11eb-9935-a051d1b56f93.png)

So each time you load a file the 3D origin trihedron will be hidden by default so the "fit all" action will behave as you expect.

**Comment by HuguesDelorme** [comment]
Acceptable workaround exists
